{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n  +4\n  -5", "trace": "def test_answer():\n>       assert func(3) == 5\nE       assert 4 == 5\nE         +4\nE         -5\n\nPython_Pytest\\com\\kxj\\case\\test_01_simple.py:8: AssertionError"}, "start": 1617330625576, "stop": 1617330625576, "uuid": "c580a7ad-7496-4404-9479-6546ca9bbafc", "historyId": "fd71fd0e5463913ef33bc72728f267c2", "testCaseId": "6a5251125706be4eeee55b1bbed380cc", "fullName": "com.kxj.case.test_01_simple#test_answer", "labels": [{"name": "parentSuite", "value": "com.kxj.case"}, {"name": "suite", "value": "test_01_simple"}, {"name": "host", "value": "DESKTOP-4IJL66C"}, {"name": "thread", "value": "3396-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "com.kxj.case.test_01_simple"}]}